comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

coverage:
  status:
    project:
      default:
        target: 70%        # Enforce 70% target for project coverage
        threshold: 10%
    patch:
      default:
        target: 70%        # Enforce 70% target for patch coverage
        threshold: 10%
    changes:
      default:
        target: 70%        # Enforce 70% target for changes coverage
        threshold: 10%
