comment:
  layout: "header, diff, flags, files"
coverage:
  status:
    project:
      default:
        threshold: 0%
    patch:
      default:
        threshold: 0%
    changes:
      default:
        threshold: 0%
