services:
  postgres:
    image: postgres:16
    container_name: timely-postgres
    environment:
      POSTGRES_DB: timely
      POSTGRES_USER: timely_user
      POSTGRES_PASSWORD: timely_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_v16:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timely_user -d timely"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_v16:
